"""empty message

Revision ID: 1b094e6887bf
Revises: e11c9773491d
Create Date: 2024-10-11 18:28:10.837935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b094e6887bf'
down_revision = 'e11c9773491d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tech_knowledges', schema=None) as batch_op:
        batch_op.drop_constraint('tech_knowledges_rank_id_fkey', type_='foreignkey')
        batch_op.drop_column('rank_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tech_knowledges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rank_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('tech_knowledges_rank_id_fkey', 'ranks', ['rank_id'], ['id'])

    # ### end Alembic commands ###
