"""empty message

Revision ID: be94d0b0fcf9
Revises: c2fea06edc75
Create Date: 2024-10-08 16:32:28.491350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be94d0b0fcf9'
down_revision = 'c2fea06edc75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('RankingJobPosting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_postings_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('RankingJobPosting_jobPosting_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'job_postings', ['job_postings_id'], ['id'])
        batch_op.drop_column('jobPosting_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('RankingJobPosting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jobPosting_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('RankingJobPosting_jobPosting_id_fkey', 'job_postings', ['jobPosting_id'], ['id'])
        batch_op.drop_column('job_postings_id')

    # ### end Alembic commands ###
