"""empty message

Revision ID: c2fea06edc75
Revises: 5769044fb872
Create Date: 2024-10-08 16:24:17.212428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2fea06edc75'
down_revision = '5769044fb872'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rankingJobPosting_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'RankingJobPosting', ['rankingJobPosting_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('rankingJobPosting_id')

    # ### end Alembic commands ###
