"""empty message

Revision ID: cac1c5c0df8d
Revises: be94d0b0fcf9
Create Date: 2024-10-08 16:43:34.507774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cac1c5c0df8d'
down_revision = 'be94d0b0fcf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.drop_constraint('job_postings_rankingJobPosting_id_fkey', type_='foreignkey')
        batch_op.drop_column('rankingJobPosting_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rankingJobPosting_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('job_postings_rankingJobPosting_id_fkey', 'RankingJobPosting', ['rankingJobPosting_id'], ['id'])

    # ### end Alembic commands ###
