"""empty message

Revision ID: fe838b083f31
Revises: cac1c5c0df8d
Create Date: 2024-10-11 16:16:12.841315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe838b083f31'
down_revision = 'cac1c5c0df8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ranking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rankingJobPosting',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ranking_id', sa.Integer(), nullable=False),
    sa.Column('job_posting_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ),
    sa.ForeignKeyConstraint(['ranking_id'], ['ranking.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'job_posting_id')
    )
    op.create_table('rankingApplications',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ranking_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['ranking_id'], ['ranking.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'application_id')
    )
    op.drop_table('RankingApplication')
    op.drop_table('RankingJobPosting')
    with op.batch_alter_table('post_languages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('languages_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('post_languages_language_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'languages', ['languages_id'], ['id'])
        batch_op.drop_column('language_id')

    with op.batch_alter_table('tech_knowledges', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tech_knowledges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))

    with op.batch_alter_table('post_languages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('post_languages_language_id_fkey', 'languages', ['language_id'], ['id'])
        batch_op.drop_column('languages_id')

    op.create_table('RankingJobPosting',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ranking', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('job_postings_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['job_postings_id'], ['job_postings.id'], name='RankingJobPosting_job_postings_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='RankingJobPosting_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='RankingJobPosting_pkey')
    )
    op.create_table('RankingApplication',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ranking', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('application_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name='RankingApplication_application_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='RankingApplication_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='RankingApplication_pkey')
    )
    op.drop_table('rankingApplications')
    op.drop_table('rankingJobPosting')
    op.drop_table('ranking')
    # ### end Alembic commands ###
